# Generated by Django 3.2 on 2023-08-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_auto_20230808_1529"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                verbose_name="Время приготовления (минуты)"
            ),
        ),
    ]
