# Generated by Django 3.2 on 2023-08-14 18:09

from django.db import migrations

import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_ingredient_unique_ingredient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ["name"],
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=recipes.models.NameField(
                max_length=255, verbose_name="Название ингредиента"
            ),
        ),
    ]
