# Generated by Django 3.2 on 2023-08-14 18:12

from django.db import migrations

import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_auto_20230814_2109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=recipes.models.NameField(
                max_length=255, unique=True, verbose_name="Название тега"
            ),
        ),
    ]
