# Generated by Django 3.2 on 2023-08-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_auto_20230816_2012"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"verbose_name": "Избранное"},
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="add_date",
        ),
    ]
